baseURL = "https://adamkaplan.org/"
languageCode = "en-us"
title = "Adam Kaplan"
theme = "LoveIt"

# Author config
[author]
  name = "Adam Kaplan"
  email = "adam@adamkaplan.org"
  link = ""

# Menu config
[menu]
  [[menu.main]]
    weight = 1
    identifier = "home"
    name = "Home"
    url = "/"
    # title will be shown when you hover on this menu link
    title = "Home"
  [[menu.main]]
    weight = 2
    identifier = "cv"
    name = "CV"
    url = "https://storage.adamkaplan.org/AdamKaplan.pdf"
    # title will be shown when you hover on this menu link
    title = "CV"

[params]
  # public git repo url only then enableGitInfo is true
  gitRepo = "https://github.com/adamkaplan0/adamkaplan.org"
  title = "Adam Kaplan"
  # website description for RSS, SEO, Open Graph and Twitter Cards
  description = "Hi! I'm Adam Kaplan, PhD candidate in Political Science and Statistics (joint) at the Massachusetts Institute of Technology (MIT), concentrating in political methodology and international relations. I study causal inference with time-series, develop R packages, create/lead workshops, and publish web applications to help people and make research easier and faster."

  # Header config
  [params.header]
    # Header title config
    [params.header.title]
      # title name
      name = "Adam Kaplan"
      # whether to use typeit animation for title name
      typeit = true

  # Footer config
  [params.footer]
    enable = true
    # whether to show Hugo and theme info
    hugo = true
    # whether to show copyright info
    copyright = true
    # whether to show the author
    author = true
    # site creation time
    since = 2022
    # license info (HTML format is supported)
    license= ""

  # App icon config
  [params.app]
    # optional site title override for the app when added to an iOS home screen or Android launcher
    title = "Adam Kaplan"
    # whether to omit favicon resource links
    noFavicon = false
    # modern SVG favicon to use in place of older style .png and .ico files
    svgFavicon = ""
    # Android browser theme color
    themeColor = "#f8f8f8"
    # Safari mask icon color
    iconColor = "#f8f8f8"
    # Windows v8-11 tile color
    tileColor = "#f8f8f8"

  # Home page config
  [params.home]
    # Home page profile
    [params.home.profile]
      enable = true
      # URL of avatar shown in home page
      avatarURL = "https://storage.adamkaplan.org/work-round.png"
      # title shown in home page (HTML format is supported)
      title = "Adam Kaplan"
      # subtitle shown in home page (HTML format is supported)
      subtitle = "<div align=\"left\"><p><strong>Hi!</strong> I'm Adam Kaplan, PhD candidate in Political Science and Statistics (joint) at the <a href=\"https://polisci.mit.edu/people/adam-kaplan\" style=\"border-bottom: 1px dotted;\">Massachusetts Institute of Technology (MIT)</a>, concentrating in political methodology and international relations. I study causal inference with time-series, develop R packages, create/lead workshops, and publish web applications to help people and make research easier and faster.<br><br>Currently I am working on:<ul><li>Developing a model-agnostic procedure to estimate heterogeneous treatment effects in time-series cross-sectional data and packaging it in an easy-to-use R package.</li><li>Extending an experimental design developed to estimate the effect of media source choice on polarization to account for confounding variables (with <a href=\"http://web.mit.edu/teppei/www/\" style=\"border-bottom: 1px dotted;\">Teppei Yamamoto</a>).</li><li>Maintaining the <a href=\"https://www.latextableviewer.com/\" style=\"border-bottom: 1px dotted;\">LaTeX Table Viewer</a> web application, which allows one to quickly compile LaTeX code locally, without having to have LaTeX installed.</li></ul>Outside of work, I love to rock climb, bake bread, and explore breweries in the New England area.</p></div>"
      # whether to use typeit animation for subtitle
      typeit = false
      # whether to show social links
      social = true

  # Social config in home page
  [params.social]
    GitHub = "adamkaplan0"
    Linkedin = "adamkaplan0"
    Email = "adam@adamkaplan.org"